<?php
$storeId = Mage::app()->getStore()->getStoreId();
$display_checkbox = false;
if (Mage::getStoreConfig("emailchef_newsletter/emailchef/enable_subscribe_in_checkout", $storeId) == 1) {
	if (Mage::helper('customer')->isLoggedIn()) {
		$email = Mage::helper('customer')->getCustomer()->getEmail();
		$newsletter_subscriber_model = Mage::getModel('newsletter/subscriber')->loadByEmail($email);
		if ($newsletter_subscriber_model->getSubscriberStatus() != 1) {
			$display_checkbox = true;
		}
	} else {
		$display_checkbox = true;
	}
}
?>

<?php if ($display_checkbox): ?>
	<div class="buttons-set">
		<label>
			<input type="checkbox" onchange="emailchefModifyPost()" name="emailchef_subscribe" id="emailchef_subscribe" value="1" title="<?php echo $this->htmlEscape($this->__('Sign Up for Newsletter')) ?>" checked="checked" />
			<?php echo $this->htmlEscape($this->__('Sign Up for Newsletter')) ?>
		</label>
	</div>
    <script type="text/javascript">
        emailchefModifyPost = function () {
            if ($('emailchef_subscribe2')) $('emailchef_subscribe2').remove();
            if ($('emailchef_subscribe').checked) {
                var newinput = new Element("input", {name: "emailchef_subscribe2", id: "emailchef_subscribe2", value: "1", type: "hidden"});
                try {
                    Element.insert(Form.findFirstElement(payment.form), newinput);
                } catch (e) {
                    $("co-payment-form").insert(newinput);
                }
            }
        }
        emailchefModifyPost();
    </script>
<?php endif; ?>