<?php
/**
 * This file is solely to instantiate the javascript in system config with values that can only be generated via php
 */
?>
<script language="JavaScript">
    // Initialise observer so that when list is changed, groups are reloaded
    urlGroup = '<?php echo Mage::getModel('adminhtml/url')->getUrl("emailchef/adminhtml_configuration/getgroups"); ?>';
    document.observe("dom:loaded", function() {
        initListObserver(urlGroup);
    });
    // Initialise observer to run self-test
    urlTest = '<?php echo Mage::getModel('adminhtml/url')->getUrl("emailchef/adminhtml_configuration/testconnection"); ?>';
    urlList = '<?php echo Mage::getModel('adminhtml/url')->getUrl("emailchef/adminhtml_configuration/getlists"); ?>';
    urlCreateFields = '<?php echo Mage::getModel('adminhtml/url')->getUrl("emailchef/adminhtml_configuration/createfields"); ?>';
    document.observe("dom:loaded", function() {
        initSelfTestObserver(urlTest,urlList);
        initCreateFieldsObserver(urlCreateFields);
    });
</script>
